### ISSUE TITLE
non-integral table row heights

### ISSUE THREAD

**Issue by maksa** [davidman/DHSmartScreenshot#4]
Great work.

Just want to add this for the next person that might run into this - if one is for some reason having non-pixel-perfect row heights (e.g. calculated dynamically) that end up having non-integral values, created final image will be off (different from the original table rendering) since cell UImages that are created by the library and slapped together will have heights truncated to integers and error (difference) will accumulate. 

Other than that (which was actually my problem, not library's) - really nice piece of work. 

Thanks again.

**Comment by davidman** [comment]
Hi maksa,

This bug has been fixed, thanks for your comments!

Sincerely,
David.
