### ISSUE TITLE
navigationbar not captured

### ISSUE THREAD

**Issue by i0sdev** [davidman/DHSmartScreenshot#8]
How to include the navigationbar when snapshot?

**Comment by davidman** [comment]
Hi iOSdev, 

You can accomplish what you want by importing these files to your project:

#import "UIView+DHSmartScreenshot.h"
#import "UIImage+DHImageAdditions.h"

Then, use this code:

UIImage *tableViewWithNavBarImage = [UIImage verticalImageFromArray:@[[self.navigationController.navigationBar screenshot], [self.tableView screenshot]]];

And, ...voila!

Let me know if that worked!

Best regards,
David.

**Comment by i0sdev** [comment]
thank you. But it's really **only** navigation bar.
What I mean is to include status bar too. I tried `[UIImage verticalImageFromArray:@[[[[UIApplication sharedApplication] keyWindow] screenshot], [self.tableView screenshot]]];`, but found only status bar background color is in the image, but no content (carrier icon, wifi, date, battery....)

**Comment by davidman** [comment]
Oh, I see... sadly, there is no way to get a status bar screenshot with all the contents you expect, as far as I can tell you. That is because you don't get a reference to the status bar view in any of your app's windows. You can get the frame and so, though, and no more than that.
